# Generated by Django 2.2.7 on 2019-12-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='exam_problem',
            old_name='exam_id',
            new_name='exam',
        ),
        migrations.RenameField(
            model_name='exam_problem',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='exam_user',
            old_name='exam_id',
            new_name='exam',
        ),
        migrations.RenameField(
            model_name='exam_user',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='user_id',
            new_name='user',
        ),
    ]
