# Generated by Django 2.2.7 on 2019-12-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0002_auto_20191203_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='OJ_AC_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='OJ_CE_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='OJ_RE_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='OJ_WA_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='submit_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
