# Generated by Django 2.2.7 on 2019-12-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0004_auto_20191218_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='OJ_AC_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='OJ_CE_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='OJ_RE_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='OJ_WA_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='submit_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='solved_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='submit_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
