# Generated by Django 2.2.7 on 2019-12-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0006_auto_20191225_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chek',
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
