# Generated by Django 2.2.7 on 2019-12-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Judge', '0007_auto_20191225_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='problem',
        ),
    ]
